---
title: "AMVR Tracking"
author: [Lars Gielen, Jan-Mathijs Pex, Vinz Roosen]
date: ""
lang: "nl"

# Headers and footers
disable-header-and-footer: false
header-left: "\\thetitle"
header-center: "\\leftmark"
header-right: "\\theauthor"
footer-left: "\\leftmark"
footer-center: "\\leftmark"
footer-right: "Page \\thepage"
footnotes-pretty: true

# sections
numbersections: true

# captions:
caption-justification: centering # justified - raggedright

# Code blocks
listings: true
listings-disable-line-numbers: true
listings-no-page-break: true

# Title Page
titlepage: false
titlepage-color: "D8DE2C"
titlepage-text-color: "5F5F5F"
titlepage-rule-color: "435488"
titlepage-logo: ""
titlepage-background: ""

# Table of Contents
toc: false
toc-own-page: false

# cross-ref
figPrefix:
  - "figuur"
  - "figuren"

tblPrefix:
  - "tabel"
  - "tabellen"

figureTitle: "Figuur"
tableTitle: "Tabel"
...

